import type {
  DashboardSnapshot,
  ResearchDossier,
  ResearchDossierDetail,
  StudioRenderJob,
  StudioAsset,
  StudioChannel,
  StudioProject
} from "./studio-types";

const createdAt = "2026-06-26T00:00:00.000Z";

export const mockChannels: StudioChannel[] = [
  {
    id: "channel-anime-lore",
    name: "Anime Lore",
    niche: "Universos anime, teorias e explicacoes de lore",
    language: "pt-BR",
    visualStyle: "Cortes dramaticos, overlays editoriais e close-ups intensos",
    narrativeTone: "Analitico com suspense",
    defaultTemplate: "anime_dark",
    defaultRenderMode: "cinematic_v2",
    defaultRenderQuality: "high",
    defaultAudioMood: "dark_suspense",
    defaultCaptionStyle: "anime_punch",
    defaultVisualPreset: "mystery",
    defaultMusicAssetId: "asset-music-001",
    defaultVoiceoverAssetId: "asset-voice-001",
    defaultDurationTarget: 32,
    defaultSceneDuration: 4.2,
    preferredAssetCategories: ["PANEL", "BACKGROUND", "CHARACTER"],
    preferredAssetTags: ["anime", "lore", "uchiha", "suspense"],
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "channel-hqs-comentadas",
    name: "HQs Comentadas",
    niche: "Resumos e opinioes sobre quadrinhos e sagas classicas",
    language: "pt-BR",
    visualStyle: "Painel editorial com zooms ritmados e captions bold",
    narrativeTone: "Explicativo com energia de review",
    defaultTemplate: "comic_drama",
    defaultRenderMode: "cinematic_v2",
    defaultRenderQuality: "standard",
    defaultAudioMood: "documentary_bed",
    defaultCaptionStyle: "comic_pop",
    defaultVisualPreset: "drama",
    defaultMusicAssetId: null,
    defaultVoiceoverAssetId: null,
    defaultDurationTarget: 38,
    defaultSceneDuration: 4.8,
    preferredAssetCategories: ["COVER", "PANEL", "SCREENSHOT"],
    preferredAssetTags: ["hq", "comic", "review", "batman"],
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "channel-curiosidades-sombrias",
    name: "Curiosidades Sombrias",
    niche: "Historias inquietantes, misterios e curiosidades obscuras",
    language: "pt-BR",
    visualStyle: "Texturas escuras, silhuetas e contraste alto",
    narrativeTone: "Misterioso e provocativo",
    defaultTemplate: "true_crime",
    defaultRenderMode: "cinematic_v2",
    defaultRenderQuality: "high",
    defaultAudioMood: "horror_tension",
    defaultCaptionStyle: "horror_whisper",
    defaultVisualPreset: "horror",
    defaultMusicAssetId: "asset-music-001",
    defaultVoiceoverAssetId: "asset-voice-001",
    defaultDurationTarget: 34,
    defaultSceneDuration: 4,
    preferredAssetCategories: ["BROLL", "BACKGROUND", "SCREENSHOT"],
    preferredAssetTags: ["sombrio", "misterio", "crime", "arquivo"],
    createdAt,
    updatedAt: createdAt
  }
];

export const mockAssets: StudioAsset[] = [
  {
    id: "asset-anime-001",
    filename: "uchiha-panel-01.png",
    originalName: "uchiha-panel-01.png",
    path: "storage/assets/panel/image/uchiha-panel-01.png",
    type: "IMAGE",
    category: "PANEL",
    franchise: "Naruto",
    character: "Itachi Uchiha",
    emotion: "MYSTERIOUS",
    tags: ["anime", "lore", "uchiha", "hook"],
    licenseType: "editorial-reference",
    copyrightRisk: "HIGH",
    recommendedUse: "Aberturas de reels narrativos",
    duration: null,
    width: 1080,
    height: 1920,
    mimeType: "image/png",
    extension: ".png",
    fileSize: 284000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-anime-002",
    filename: "village-corridor-shot.jpg",
    originalName: "village-corridor-shot.jpg",
    path: "storage/assets/background/image/village-corridor-shot.jpg",
    type: "IMAGE",
    category: "BACKGROUND",
    franchise: "Naruto",
    character: null,
    emotion: "DARK",
    tags: ["anime", "vila", "suspense"],
    licenseType: "editorial-reference",
    copyrightRisk: "HIGH",
    recommendedUse: "Planos de respiracao entre falas densas",
    duration: null,
    width: 1080,
    height: 1920,
    mimeType: "image/jpeg",
    extension: ".jpg",
    fileSize: 412000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-hq-001",
    filename: "batman-cover-issue-01.jpg",
    originalName: "batman-cover-issue-01.jpg",
    path: "storage/assets/cover/image/batman-cover-issue-01.jpg",
    type: "IMAGE",
    category: "COVER",
    franchise: "Batman",
    character: "Batman",
    emotion: "DARK",
    tags: ["hq", "batman", "capa"],
    licenseType: "editorial-reference",
    copyrightRisk: "HIGH",
    recommendedUse: "Capas e aberturas de episodios comentados",
    duration: null,
    width: 1080,
    height: 1920,
    mimeType: "image/jpeg",
    extension: ".jpg",
    fileSize: 503000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-dark-001",
    filename: "shadow-realm-clip.mp4",
    originalName: "shadow-realm-clip.mp4",
    path: "storage/assets/broll/video/shadow-realm-clip.mp4",
    type: "VIDEO",
    category: "BROLL",
    franchise: null,
    character: null,
    emotion: "TENSE",
    tags: ["sombrio", "misterio", "broll"],
    licenseType: "owned-original",
    copyrightRisk: "LOW",
    recommendedUse: "Textura de transicao para blocos sombrios",
    duration: 4.2,
    width: 1080,
    height: 1920,
    mimeType: "video/mp4",
    extension: ".mp4",
    fileSize: 2480000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-music-001",
    filename: "ambient-dark-bed.wav",
    originalName: "ambient-dark-bed.wav",
    path: "storage/assets/track/music/ambient-dark-bed.wav",
    type: "MUSIC",
    category: "TRACK",
    franchise: null,
    character: null,
    emotion: "DARK",
    tags: ["audio", "music", "dark", "bed"],
    licenseType: "local-generated",
    copyrightRisk: "LOW",
    recommendedUse: "Base musical para narrativas sombrias",
    duration: 18,
    width: null,
    height: null,
    mimeType: "audio/wav",
    extension: ".wav",
    fileSize: 1640000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    musicProfile: {
      assetId: "asset-music-001",
      title: "Ambient Dark Bed",
      artist: "ReelForge Mock Library",
      sourceType: "user_owned",
      licenseStatus: "owned",
      mood: "dark",
      genre: "cinematic",
      bpm: 88,
      bpmConfidence: 0.62,
      energy: "medium",
      useCase: "true_crime",
      durationSeconds: 18,
      loudness: -17.8,
      beatMarkers: [
        { timeSeconds: 0, strength: 0.62, confidence: 0.5 },
        { timeSeconds: 4.1, strength: 0.71, confidence: 0.58 },
        { timeSeconds: 8.2, strength: 0.77, confidence: 0.64 },
        { timeSeconds: 12.3, strength: 0.8, confidence: 0.66 }
      ],
      energyTimeline: [
        { timeSeconds: 0, energy: 34 },
        { timeSeconds: 6, energy: 48 },
        { timeSeconds: 12, energy: 58 },
        { timeSeconds: 18, energy: 44 }
      ],
      notes: "Bed escura para narrativas densas e misterio documental.",
      safetyWarning: null,
      createdAt,
      updatedAt: createdAt
    },
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-music-002",
    filename: "stadium-hype-phonk.wav",
    originalName: "stadium-hype-phonk.wav",
    path: "storage/assets/track/music/stadium-hype-phonk.wav",
    type: "MUSIC",
    category: "TRACK",
    franchise: null,
    character: null,
    emotion: "EPIC",
    tags: ["music", "football", "phonk", "hype", "beat"],
    licenseType: "owned-original",
    copyrightRisk: "LOW",
    recommendedUse: "Reels de futebol, cortes rapidos e microclips de impacto",
    duration: 24,
    width: null,
    height: null,
    mimeType: "audio/wav",
    extension: ".wav",
    fileSize: 2140000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: "Drop forte no segundo 8 para inserts esportivos.",
    musicProfile: {
      assetId: "asset-music-002",
      title: "Stadium Hype Phonk",
      artist: "ReelForge Mock Library",
      sourceType: "user_owned",
      licenseStatus: "owned",
      mood: "hype",
      genre: "phonk",
      bpm: 156,
      bpmConfidence: 0.84,
      energy: "high",
      useCase: "football",
      durationSeconds: 24,
      loudness: -13.1,
      beatMarkers: [
        { timeSeconds: 0, strength: 0.88, confidence: 0.82 },
        { timeSeconds: 3.08, strength: 0.92, confidence: 0.84 },
        { timeSeconds: 6.15, strength: 0.94, confidence: 0.86 },
        { timeSeconds: 9.23, strength: 0.97, confidence: 0.88 }
      ],
      energyTimeline: [
        { timeSeconds: 0, energy: 62 },
        { timeSeconds: 6, energy: 80 },
        { timeSeconds: 12, energy: 92 },
        { timeSeconds: 18, energy: 84 },
        { timeSeconds: 24, energy: 68 }
      ],
      notes: "Faixa de ataque rapido para presets football_hype e viral_fast_cut.",
      safetyWarning: null,
      createdAt,
      updatedAt: createdAt
    },
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-music-003",
    filename: "documentary-clean-bed.wav",
    originalName: "documentary-clean-bed.wav",
    path: "storage/assets/track/music/documentary-clean-bed.wav",
    type: "MUSIC",
    category: "TRACK",
    franchise: null,
    character: null,
    emotion: "NEUTRAL",
    tags: ["music", "documentary", "clean", "ambient"],
    licenseType: "royalty-free-pack",
    copyrightRisk: "LOW",
    recommendedUse: "Narrativas explicativas com voz em primeiro plano",
    duration: 26,
    width: null,
    height: null,
    mimeType: "audio/wav",
    extension: ".wav",
    fileSize: 2420000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: "royalty_free",
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: "Bed discreta para documentario e shorts limpos.",
    musicProfile: {
      assetId: "asset-music-003",
      title: "Documentary Clean Bed",
      artist: "Royalty Pack Mock",
      sourceType: "royalty_free",
      licenseStatus: "royalty_free",
      mood: "documentary",
      genre: "ambient",
      bpm: 96,
      bpmConfidence: 0.58,
      energy: "low",
      useCase: "documentary",
      durationSeconds: 26,
      loudness: -18.9,
      beatMarkers: [
        { timeSeconds: 0, strength: 0.42, confidence: 0.4 },
        { timeSeconds: 5, strength: 0.5, confidence: 0.46 },
        { timeSeconds: 10, strength: 0.54, confidence: 0.48 }
      ],
      energyTimeline: [
        { timeSeconds: 0, energy: 22 },
        { timeSeconds: 8, energy: 28 },
        { timeSeconds: 16, energy: 30 },
        { timeSeconds: 24, energy: 24 }
      ],
      notes: "Faixa limpa com foco em inteligibilidade da voz.",
      safetyWarning: null,
      createdAt,
      updatedAt: createdAt
    },
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-voice-001",
    filename: "narration-guide.wav",
    originalName: "narration-guide.wav",
    path: "storage/assets/track/audio/narration-guide.wav",
    type: "AUDIO",
    category: "TRACK",
    franchise: null,
    character: null,
    emotion: "NEUTRAL",
    tags: ["audio", "voiceover", "guide"],
    licenseType: "local-generated",
    copyrightRisk: "LOW",
    recommendedUse: "Guia de narracao para testes locais",
    duration: 14,
    width: null,
    height: null,
    mimeType: "audio/wav",
    extension: ".wav",
    fileSize: 1280000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-sfx-001",
    filename: "impact-hit.wav",
    originalName: "impact-hit.wav",
    path: "storage/assets/effect/sfx/impact-hit.wav",
    type: "SFX",
    category: "EFFECT",
    franchise: null,
    character: null,
    emotion: "TENSE",
    tags: ["audio", "sfx", "impact"],
    licenseType: "local-generated",
    copyrightRisk: "LOW",
    recommendedUse: "Impacto de corte ou revelacao",
    duration: 0.6,
    width: null,
    height: null,
    mimeType: "audio/wav",
    extension: ".wav",
    fileSize: 64000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: null,
    sfxProfile: {
      assetId: "asset-sfx-001",
      title: "Impact Hit",
      category: "impact",
      intensity: "high",
      durationSeconds: 0.6,
      useCase: "impact_moment",
      licenseStatus: "owned",
      notes: "Hit principal para reveals e cortes de climax.",
      createdAt,
      updatedAt: createdAt
    },
    createdAt,
    updatedAt: createdAt
  },
  {
    id: "asset-sfx-002",
    filename: "transition-whoosh.wav",
    originalName: "transition-whoosh.wav",
    path: "storage/assets/effect/sfx/transition-whoosh.wav",
    type: "SFX",
    category: "EFFECT",
    franchise: null,
    character: null,
    emotion: "CURIOUS",
    tags: ["audio", "sfx", "whoosh", "transition"],
    licenseType: "owned-original",
    copyrightRisk: "LOW",
    recommendedUse: "Transicoes de impacto e entradas de microclip",
    duration: 0.8,
    width: null,
    height: null,
    mimeType: "audio/wav",
    extension: ".wav",
    fileSize: 72000,
    sourceProvider: null,
    sourceUrl: null,
    sourceAuthor: null,
    sourceLicense: null,
    sourceLicenseUrl: null,
    downloadedAt: null,
    collectionId: null,
    usageNotes: "Whoosh curto para acompanhar flash e cuts ritmados.",
    sfxProfile: {
      assetId: "asset-sfx-002",
      title: "Transition Whoosh",
      category: "whoosh",
      intensity: "medium",
      durationSeconds: 0.8,
      useCase: "transition",
      licenseStatus: "owned",
      notes: "Whoosh de transicao para presets viral_fast_cut e football_hype.",
      createdAt,
      updatedAt: createdAt
    },
    createdAt,
    updatedAt: createdAt
  }
];

export const mockProjects: StudioProject[] = [
  {
    id: "proj-anime-lore-001",
    title: "A queda do cla Uchiha em 3 atos",
    status: "SCENE_PLANNING",
    channelId: "channel-anime-lore",
    channel: mockChannels[0]!,
    script:
      "Hook sobre o misterio do cla. Contexto rapido sobre a tensao politica. Fechamento com pergunta para a audiencia.",
    durationTarget: 30,
    format: "9:16",
    templateId: "anime_dark",
    editingReferencePresetId: "builtin-true-crime-casefile",
    editingStyleSummary: {
      presetId: "builtin-true-crime-casefile",
      presetName: "True Crime Casefile",
      useCase: "true_crime",
      pacing: "fast",
      cutPace: 2.8,
      zoomStyle: "subtle",
      flashStyle: "low",
      transitionStyle: "mixed",
      captionStyle: "lower_clean",
      narrationStyle: "documentary",
      musicStyle: "dark",
      sfxStyle: "medium",
      hookStyle: "warning",
      ctaStyle: "subtle",
      microclipPlacement: "middle",
      defaultShotDurationSeconds: 2.8,
      recommendedMusicPresetId: "true_crime_dark",
      recommendedAudioMasteringPresetId: "true_crime_dark",
      recommendedNarrationVoicePackId: "true_crime_dark_ptbr",
      notes: "Equilibra contexto, inserts curtos e fechamento investigativo."
    },
    defaultCaptionStyle: "anime_punch",
    backgroundMusicAssetId: "asset-music-001",
    musicPresetId: "true_crime_dark",
    voiceoverAssetId: "asset-voice-001",
    audioMood: "dark_suspense",
    musicVolume: 0.16,
    voiceVolume: 1,
    sfxVolume: 0.72,
    enableAudioDucking: true,
    duckingLevel: 0.35,
    createdAt,
    updatedAt: createdAt,
    scenes: [
      {
        id: "scene-anime-001",
        order: 1,
        title: "Hook sombrio",
        narrationText:
          "Pouca gente percebe como a tragedia comecou muito antes da noite final.",
        captionText: "A historia comecou antes do massacre",
        duration: 7.5,
        emotion: "MYSTERIOUS",
        assetId: "asset-anime-001",
        asset: mockAssets[0]!,
        sfxAssetId: "asset-sfx-001",
        sfxStartTime: 0.2,
        sfxVolume: 0.74,
        visualPreset: "mystery",
        transition: "flash-cut",
        captionStyle: "anime_punch",
        captionPosition: "split",
        captionEmphasisWords: ["historia", "massacre"],
        energyLevel: 88,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "scene-anime-002",
        order: 2,
        title: "Contexto do conflito",
        narrationText:
          "A ruptura entre poder, vigilancia e medo transformou cada gesto em suspeita.",
        captionText: "Quando medo e poder se misturam",
        duration: 11,
        emotion: "DARK",
        assetId: "asset-anime-002",
        asset: mockAssets[1]!,
        sfxAssetId: "asset-sfx-001",
        sfxStartTime: 0.9,
        sfxVolume: 0.62,
        visualPreset: "horror",
        transition: "fade",
        captionStyle: "horror_whisper",
        captionPosition: "lower-third",
        captionEmphasisWords: ["medo", "poder"],
        energyLevel: 64,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "scene-anime-003",
        order: 3,
        title: "Cliffhanger final",
        narrationText:
          "E se o verdadeiro ponto de nao retorno tiver acontecido muito antes do que contam?",
        captionText: "O ponto de nao retorno veio antes?",
        duration: 8.5,
        emotion: "CURIOUS",
        assetId: null,
        asset: null,
        sfxAssetId: "asset-sfx-001",
        sfxStartTime: 0.35,
        sfxVolume: 0.68,
        visualPreset: "suspense",
        transition: "hard-cut",
        captionStyle: null,
        captionPosition: null,
        captionEmphasisWords: ["ponto", "retorno"],
        energyLevel: 74,
        createdAt,
        updatedAt: createdAt
      }
    ]
  }
];

export const mockRenderJobs: StudioRenderJob[] = [];

export const mockResearchDossiers: ResearchDossier[] = [
  {
    id: "dossier-estacao-aurora",
    channelId: "channel-curiosidades-sombrias",
    channel: mockChannels[2]!,
    title: "Dossie: O caso da Estacao Aurora",
    topic: "desaparecimento da equipe da Estacao Aurora",
    niche: "documentario sombrio",
    tone: "investigativo",
    targetDuration: 42,
    status: "ready_for_review",
    summary:
      "O dossie organiza a cronologia do desaparecimento ficticio da Estacao Aurora com foco em fatos confirmados, ultimo sinal e pontos ainda incertos.",
    narrativeAngle:
      "Reconstruir a ultima madrugada da equipe e mostrar onde o caso deixa de parecer falha tecnica e vira misterio.",
    editorialNotes:
      "Abrir com o ultimo sinal. Ancorar a cronologia no relatorio. Encerrar com a divergencia entre diario e versao oficial.",
    safetyNotes:
      "Caso ficticio usado para demonstracao local. Alegacoes sem fonte devem permanecer incertas.",
    sourceCount: 2,
    approvedSourceCount: 2,
    factCount: 2,
    timelineCount: 2,
    outlineSceneCount: 3,
    createdAt,
    updatedAt: createdAt
  }
];

export const mockResearchDossierDetails: ResearchDossierDetail[] = [
  {
    dossier: mockResearchDossiers[0]!,
    sources: [
      {
        id: "source-aurora-001",
        dossierId: "dossier-estacao-aurora",
        title: "Relatorio tecnico da Estacao Aurora",
        url: "https://example.invalid/aurora-report",
        provider: "manual",
        sourceType: "official_record",
        author: "Conselho Orbital",
        publishedAt: "1998",
        accessedAt: createdAt,
        reliabilityScore: 91,
        citationText: "Relatorio tecnico emitido apos a perda de contato com a estacao.",
        rawTextPath: null,
        excerpt:
          "O relatorio confirma a perda de energia na madrugada e registra um ultimo sinal manual 11 minutos antes do apagao total.",
        notes: "Fonte base para cronologia e linguagem cautelosa.",
        status: "approved",
        errorMessage: null,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "source-aurora-002",
        dossierId: "dossier-estacao-aurora",
        title: "Diario de bordo recuperado",
        url: null,
        provider: "manual",
        sourceType: "manual_note",
        author: "Arquivo interno",
        publishedAt: null,
        accessedAt: createdAt,
        reliabilityScore: 63,
        citationText: null,
        rawTextPath: null,
        excerpt:
          "Entradas finais mencionam um ruido crescente, debate na equipe e uma porta selada minutos antes do corte de energia.",
        notes: "Material parcial e provavelmente incompleto.",
        status: "approved",
        errorMessage: null,
        createdAt,
        updatedAt: createdAt
      }
    ],
    facts: [
      {
        id: "fact-aurora-001",
        dossierId: "dossier-estacao-aurora",
        sourceId: "source-aurora-001",
        claim: "A perda total de energia ocorreu na madrugada logo apos o ultimo sinal manual.",
        factType: "event",
        confidence: "confirmed",
        dateValue: "1998",
        people: [],
        places: ["Estacao Aurora"],
        tags: ["apagao", "sinal", "cronologia"],
        notes: null,
        source: null,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "fact-aurora-002",
        dossierId: "dossier-estacao-aurora",
        sourceId: "source-aurora-002",
        claim: "O diario de bordo descreve um ruido anormal e a selagem de uma porta pouco antes do apagao.",
        factType: "allegation",
        confidence: "likely",
        dateValue: null,
        people: [],
        places: ["Modulo de manutencao"],
        tags: ["ruido", "porta", "incerteza"],
        notes: "Manter como alegacao ate aparecer confirmacao cruzada.",
        source: null,
        createdAt,
        updatedAt: createdAt
      }
    ],
    timeline: [
      {
        id: "timeline-aurora-001",
        dossierId: "dossier-estacao-aurora",
        sourceId: "source-aurora-001",
        title: "Ultimo sinal manual",
        description: "A equipe envia o ultimo sinal manual 11 minutos antes do apagao total.",
        dateValue: "1998",
        order: 1,
        location: "Estacao Aurora",
        people: [],
        confidence: "confirmed",
        source: null,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "timeline-aurora-002",
        dossierId: "dossier-estacao-aurora",
        sourceId: "source-aurora-002",
        title: "Ruido e porta selada",
        description: "O diario registra ruido crescente e uma porta selada pouco antes da perda de energia.",
        dateValue: null,
        order: 2,
        location: "Modulo de manutencao",
        people: [],
        confidence: "likely",
        source: null,
        createdAt,
        updatedAt: createdAt
      }
    ],
    hooks: [
      {
        id: "hook-aurora-001",
        dossierId: "dossier-estacao-aurora",
        text: "O ultimo sinal da Estacao Aurora terminou 11 minutos antes do sumico total.",
        hookType: "mystery",
        strengthScore: 88,
        notes: "Abrir com cronologia seca e corte abrupto.",
        createdAt,
        updatedAt: createdAt
      }
    ],
    assetRequirements: [
      {
        id: "req-aurora-001",
        dossierId: "dossier-estacao-aurora",
        sceneRole: "hook",
        description: "Mapa da estacao e interface de radio para abrir o caso.",
        mediaType: "map",
        suggestedTags: ["estacao", "radio", "ultimo sinal"],
        emotion: "MYSTERIOUS",
        priority: 95,
        fulfilledAssetId: null,
        fulfilledAsset: null,
        createdAt,
        updatedAt: createdAt
      }
    ],
    outline: [
      {
        id: "outline-aurora-001",
        dossierId: "dossier-estacao-aurora",
        order: 1,
        role: "hook",
        title: "O ultimo sinal",
        narrationDraft:
          "Onze minutos antes do apagao total, a equipe da Estacao Aurora ainda conseguiu enviar um ultimo sinal manual.",
        captionDraft: "O ultimo sinal veio 11 minutos antes do sumico",
        emotion: "MYSTERIOUS",
        visualPreset: "mystery",
        assetRequirementId: "req-aurora-001",
        assetRequirement: null,
        estimatedDuration: 6.5,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "outline-aurora-002",
        dossierId: "dossier-estacao-aurora",
        order: 2,
        role: "context",
        title: "Contexto da estacao",
        narrationDraft:
          "O relatorio tecnico sustenta a cronologia oficial, mas o diario recuperado sugere uma camada de tensao pouco antes do corte.",
        captionDraft: "A versao oficial nao explica tudo",
        emotion: "DARK",
        visualPreset: "drama",
        assetRequirementId: null,
        assetRequirement: null,
        estimatedDuration: 8.2,
        createdAt,
        updatedAt: createdAt
      },
      {
        id: "outline-aurora-003",
        dossierId: "dossier-estacao-aurora",
        order: 3,
        role: "climax",
        title: "A duvida principal",
        narrationDraft:
          "O ponto mais inquietante surge quando a cronologia confirma o apagao, mas o diario ainda fala de uma porta selada e ruido crescente.",
        captionDraft: "O relatorio e o diario nao batem",
        emotion: "TENSE",
        visualPreset: "suspense",
        assetRequirementId: null,
        assetRequirement: null,
        estimatedDuration: 9.1,
        createdAt,
        updatedAt: createdAt
      }
    ]
  }
];

export const mockDashboardSnapshot: DashboardSnapshot = {
  channels: mockChannels,
  assets: mockAssets,
  projects: mockProjects,
  renders: mockRenderJobs,
  sources: {
    channels: "mock",
    assets: "mock",
    projects: "mock",
    renders: "mock"
  }
};

